<div style="color:white;
           display:fill;
           border-radius:5px;
           background-color:#5642C5;
           font-size:200%;
           font-\amily:Arial;letter-spacing:0.5px">

<p width = 20%, style="padding: 10px;
              color:white;">
Object Oriented Programming
              
</p>
</div>

Data Science Cohort Live NYC Feb 2023
<p>Phase 3: Topic 21</p>
<br>
<br>

<div align = "right">
<img src="Images/flatiron-school-logo.png" align = "right" width="200"/>
</div>

# Objectives
- Understand the concept of **classes** and **objects**
- Explain the idea that _"everything in Python is an object"_
- Use the concept of an object's **property**
- Use the concept of an object's **method**

#### Objected Oriented Programming

- We've actually been using this without realizing it.


#### Examples

- results object in statsmodels OLS fit
- requests object or BeautifulSoup objects in web scraping
- sklearn LinearRegression models
- fig and ax objects in Matplotlib

#### Object Oriented Program in a Nutshell

<center><img src = "Images/pikachu.png" width = 800 /></center>

- Class: Pokemon
- object instance of Pokemon class

- Attributes = Fields. Properties of object instance.
- Methods: an action. Can change state of object instance.

<center><img src = "Images/pikachu.png" width = 800 /></center>

-  **Class**: general class of similar objects
- Want common attributes/methods for each instantiated object

**Pokemon is general class. Pikachu is an object of class Pokemon.**

<center><img src = "Images/pikachu.png" width = 800 /></center>

<img src='http://www.expertphp.in/images/articles/ArtImgC67UTd_classes_and_objects.jpg' width=75%/>

**Fields/Attributes**:
- objects of same class share same attributes
- each attribute takes on different values for different instantiations.
    
e.g., Name, Type, Health attributes common to all pokemons


<center><img src = "Images/pikachu.png" width = 800 /></center>

**Methods**:
- Objects in given Class can execute common set of functions
- Functions can change internal state of object
    - i.e. change attributes: .evolve() can change health, name, etc.

#### Creating a class in Python

Create simple class using class constructor and initialization:

In [1]:
class Pokemon:

    def __init__(self, name, lvl, health, attack_points, defense_points):
        
        self.name = name
        self.level = lvl
        self.life = health
        self.attack_power = attack_points
        self.defense_points = defense_points
        

the __init__ method is a special function:

- the first argument is always: *self*
- *self* refers to specific instance of class. 
- the other arguments: initalization arguments 
    - user specified inputs in initializing instance.
    - can have default arguments


#### Let's see this in action 

Create an instance of a Pokemon:
- Create and instantiate a Pikachu.

In [2]:
pikachu = Pokemon('Pikachu', 2, 70, 7, 4)

Let's check out some of the attributes

In [3]:
pikachu.attack_power

7

In [4]:
class Pokemon:
    
    def __init__(self, name, lvl, health, attack_points, defense_points):
        
        self.name = name
        self.level = lvl
        self.life = health
        self.attack_power = attack_points
        self.defense_points = defense_points

- So far the class object is like a grouping of variables (like a dict). 
- Adding methods give class objects a richer structure

#### Methods

- Create functions that:
    - return object state
    - update object state (i.e. change internal attributes)
    - do it based on information external to object.


In [5]:
class Pokemon:
    
    def __init__(self, name, lvl, health, attack_points, defense_points):
        
        self.name = name
        self.level = lvl
        self.life = health
        self.attack_power = attack_points
        self.defense_points = defense_points
    
    def get_state(self):
        
        state_dict = {'name': self.name, 'level': self.level, 'life': self.life,
                     'attack': self.attack_power, 'defense': self.defense_points}
        return state_dict
        
    def evolve(self, evolved_name):
        #Change Pokemon name to given evolved name state
        self.name = evolved_name
        
        #level up the stats
        self.level += 1
        self.life += 30
        self.attack_power += 4
        self.defense_points += 3

In [6]:
pikachu = Pokemon('Pikachu', 2, 70, 7, 4)

In [7]:
pikachu.get_state()

{'name': 'Pikachu', 'level': 2, 'life': 70, 'attack': 7, 'defense': 4}

<img src = "Images/evolution_phases.jpeg" width = 700 />

In [8]:
pikachu.evolve('Raichu')

In [9]:
pikachu.get_state()

{'name': 'Raichu', 'level': 3, 'life': 100, 'attack': 11, 'defense': 7}

Let's have fun with another class:
- Create a koala class with each instance a koala that eats bunches of eucalyptus and poops.
- Each bunch of eucalyptus weighs a pound.
- Pooping gets rid of half a pound.
- If the load in the koala's belly goes past 6 pounds:
    - the koala dies by belly explosion.

<center><img src = "Images/gastro.jpg" width = 1000/></center>

Your data science instructor really doesn't get this objected oriented programming stuff! Help him out.
- Koala takes in belly_weight, name, status(defalut is "Alive)
- alive_status method that if weight > 6, status = "Dead", if not then pass. It also prints out status


In [30]:
class Koala:
    
    # first need to initialize. 
    #define relevant variables.
    def __init__(self, belly_weight, name, status="Alive"):
        self.weight = belly_weight
        self.name = name
        self.status = status
        
    
    def alive_status(self):
        if self.weight > 6:
            self.status = "Dead"
        else:
            pass
        return self.status

       
    # eat_eucalyptus() method     
    def eat_eucalyptus(self, num_bunches = 1):
        if self.status == 'Alive':
            self.weight += num_bunches
        else:
            print("Dead koalas don't eat")
        

    # poop() method
    def poop(self, poop_weight = 0.5):
        if self.status == 'Alive':
            self.weight -= poop_weight
        else:
            print("Dead koalas don't poop.")
    
    
    

In [31]:
koala1 = Koala(1, 'Randy')
koala1.eat_eucalyptus()

In [32]:
koala1.eat_eucalyptus(2)

In [33]:
koala1.alive_status()

'Alive'

In [34]:
koala1.poop()

In [35]:
koala1.weight

3.5


- Each bunch of eucalyptus weighs a pound.
- Pooping gets rid of half a pound.
- If the load in the koala's belly goes past 6 pounds:
    - the koala dies by belly explosion.

Now for why all this is relevant to our work in data science.

In [36]:
class Standardizer:
    
    def __init__(self):
        self.mean_series = None
        self.stdev_series = None
    
    def fit(self, data):
        self.mean_series = data.mean()
        self.stdev_series = data.std(ddof = 1)
        
    def transform(self, X):
        X_standard = (X - self.mean_series)/self.stdev_series 
        return X_standard
    
    def fit_transform(self, X):
        #fit with X
        self.fit(X)
        #apply transformation to X
        transformed = self.transform(X)
        return transformed      

In [37]:
import pandas as pd
heart_df = pd.read_csv('Data/heart.csv', usecols = ['age', 'chol', 'thalach', 'target'])
heart_df.head()

age  chol  thalach  target
0   63   233      150       1
1   37   250      187       1
2   41   204      172       1
3   56   236      178       1
4   57   354      163       1

Split into train and test sets.

In [38]:
from sklearn.model_selection import train_test_split
X = heart_df.drop(columns = ['target'])
y = heart_df['target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

Let's use our standardizer class! 
- Instantiate transformer object.
- Fit our standardizer object to the training set.

In [39]:
sd = Standardizer()

In [40]:
sd.mean_series

In [41]:
sd.stdev_series

Fit the transformer.

In [42]:
sd.fit(X_train)

In [43]:
sd.mean_series

age         54.694215
chol       245.206612
thalach    148.520661
dtype: float64

In [44]:
sd.stdev_series

age         9.115527
chol       52.721364
thalach    23.157265
dtype: float64

Means and standard deviations for each column:
- extracted (fit) from training set.
- use these parameters to transform both train and test

#### Transform train set

In [45]:
X_train_standard = sd.transform(X_train)
X_train_standard.head()

age      chol   thalach
57  -1.063484  0.280596  1.575287
116 -1.502295 -0.591916  0.841176
289  0.033546 -0.762625 -0.799778
83  -0.295563  1.001366  1.273006
185 -1.173187  0.849625  0.193431

In [46]:
X_train_standard.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 242 entries, 57 to 217
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   age      242 non-null    float64
 1   chol     242 non-null    float64
 2   thalach  242 non-null    float64
dtypes: float64(3)
memory usage: 7.6 KB


In [47]:
X_train_standard.std()

age        1.0
chol       1.0
thalach    1.0
dtype: float64

#### Transform test set
- Use fitted parameters to transform test set.

In [48]:
X_test_standard = sd.transform(X_test)
X_test_standard.head()

age      chol   thalach
8   -0.295563 -0.876431  0.582078
52   0.801466 -0.269466 -0.108850
136  0.582060 -1.274751 -2.267999
243  0.252951  0.546143 -2.613463
19   1.569387 -0.117725  0.107065

In [49]:
X_test_standard.std()

age        0.976678
chol       0.916509
thalach    0.927517
dtype: float64

Scikit-learn transformers are instances of class objects.

In [50]:
from sklearn.preprocessing import StandardScaler
sklearn_sd = StandardScaler()

X_train_sklearn = sklearn_sd.fit_transform(X_train)

In [51]:
sklearn_sd.mean_

array([ 54.69421488, 245.20661157, 148.52066116])

In [52]:
sklearn_sd.scale_

array([ 9.0966736 , 52.61232256, 23.10936956])

Looking at the desciptive statistics of the transformed $X_{train}$:

In [53]:
print(X_train_sklearn.mean(axis = 0))

[-1.46806350e-17  8.07434927e-17  1.54146668e-16]


In [54]:
print(X_train_sklearn.std(axis = 0))

[1. 1. 1.]


Yeah, its doing the same thing as our hard-coded class.

#### Models in scikit-learn
- Also classes with different methods.
- .fit()
- .predict()
- .fit_predict()
- .score(X,y)

LinearRegression() was an example.

In [55]:
from numpy import linalg # linear algebra subpackage
import numpy as np

Implementing custom OLS linear regression class:
- sklearn model doing similar things under hood of
    - .fit(X,y) method
    - .predict(X) method
    - etc.

In [56]:
class CustomLinearRegression:
    
    def __init__(self):
        self.intercept = None
        self.coeff = None
        
    def fit(self, X_in, y):
        
        #create a column of 1s for offset fitting
        bias_col = np.ones(X_in.shape[0]).reshape(-1,1) 
    
        #augmented data matrix with column of ones
        X = np.hstack((bias_col, X_in))
        
        # weights: result of least squares minimization
        w = linalg.inv(X.T@X)@(X.T@y)
        # its a formula
        
        self.intercept = w[0]
        self.coeff = w[1::]
        
    # same as y = beta_0 + beta_1*x_1 + beta_2*x_2 + ... + beta_n*x_n
    #just more compact. we'll see later.
    def predict(self, X):
        y_pred = X@self.coeff + self.intercept
        return y_pred
    

Create instances of our custom model and scikit-learn linear regression model

In [57]:
from sklearn.linear_model import LinearRegression
clr = CustomLinearRegression()
sklearn_lr = LinearRegression()

Scikit-learn linear regression .fit() method:
- find weights/model parameters

In [58]:
clr.fit(X_train, y_train)
sklearn_lr.fit(X_train, y_train)

LinearRegression()

In [59]:
clr.coeff

array([-0.00507049, -0.00063573,  0.00834202])

In [60]:
sklearn_lr.coef_

array([-0.00507049, -0.00063573,  0.00834202])


Under the hood, sklearn model is:

Class object with model parameters as attributes.

- .fit(X,y) method uses formula or algorithm to find model parameters (weights)
- used X, y as training data

- .predict(X) 
    - learned parameters + X into model
    - get prediction

In [61]:
clr.predict(X_test).iloc[0:5]

8      0.680274
52     0.475754
136    0.102487
243   -0.010068
19     0.476885
dtype: float64

In [62]:
sklearn_lr.predict(X_test)[0:5]

array([ 0.6802741 ,  0.47575362,  0.10248696, -0.01006754,  0.47688451])

We showed:
- Clearly how sklearn works under the hood via class objects   
- But not integrated into the scikit-learn library
    


Next: 
- Learn about parent/child classes
- Inheritance and class hierarchy
- Integrate our models/transformers into scikit-learn class hierarchy.

# Level Up: Variables

Python is dynamically typed, meaning you don't have to instruct it as to what type of object your variable is.  
A variable is a pointer to where an object is stored in memory.

In [63]:
x = 3
print(id(x))
print(hex(id(x)))

4346456480
0x10311a9a0


In [64]:
y = 3
hex(id(y))

'0x10311a9a0'

In [65]:
x is y

True

In [66]:
# this can have implications 

x_list = [1,2,3,4]
y_list = x_list

In [67]:
x_list.pop()
print(x_list)
print(y_list)

[1, 2, 3]
[1, 2, 3]


In [68]:
# when you use copy(), you create a shallow copy of the object

z_list = y_list.copy()

In [69]:
id(z_list)

140666246367808

In [70]:
id(y_list)

140666246387776

In [71]:
y_list.pop()
print(y_list)
print(z_list)

[1, 2]
[1, 2, 3]


In [72]:
a_list = [[1,2,3], [4,5,6]]
b_list = a_list.copy()
a_list[0][0] ='z'
b_list

[['z', 2, 3], [4, 5, 6]]

In [73]:
import copy

# deepcopy is needed for mutable objects

a_list = [[1,2,3], [4,5,6]]
b_list = copy.deepcopy(a_list)
a_list[0][0] ='z'
b_list

[[1, 2, 3], [4, 5, 6]]

For more details on this general feature of Python, see [here](https://jakevdp.github.io/WhirlwindTourOfPython/03-semantics-variables.html).
For more on shallow and deep copying, go [here](https://docs.python.org/3/library/copy.html#copy.deepcopy).

# Level Up: `*args` and `**kwargs`

There are times when we want to have more flexibility in how we pass parameters to our functions/methods.

There's a whole lot we can discuss on this (checkout the [argument](https://docs.python.org/3/glossary.html#term-argument) & [parameter](https://docs.python.org/3/glossary.html#term-parameter) documentation for more details), but specifically we'll briefly discuss using `*args` and `**kwargs` in our functions/methods

> **NOTE**
>
> `*args` and `**kwargs` can be used in methods (functions associated with classes & objects) or in plain functions

## `*` Operator: `*args`

The single-asterisk operator `*` can be used to unpack iterables.

In [74]:
def product(factor1, factor2):
    out = factor1 * factor2
    return out

But if I want the product of *three* numbers this function won't do:

```python
product(3, 5, 6)
```

A nice way around this problem is to use the `*` operator.

In [75]:
def product_better(*factors):
    out = 1
    for f in factors:
        out *= f
    return out

In [76]:
product_better(2)

2

In [77]:
product_better(2, 4)

8

In [78]:
product_better(2, 4, 8, 16, 32)

32768

We can also use this notation to unpack an iterable to a function and will use each value as a _positional parameter_.

In [79]:
my_list_of_numbers = [1,2,3,4,5]

print(*my_list_of_numbers)
product_better(*my_list_of_numbers)

1 2 3 4 5


120

In [80]:
# Works for other iterables too!

my_range = range(2,10,2)

print(*my_range)
product_better(*my_range)

2 4 6 8


384

## `**` Operator: `*kwargs`

The double-asterisk operator  `∗∗`  is used for _keyword arguments_, i.e. _named arguments_.


In [81]:
def hello_to_the_office(**kwargs):
    hello_strs = []
    # Iterate through each item of kwargs (a dictionary!)
    for position_title, name in kwargs.items():
        # Note that the keys are going to be treated as a string
        hello_strs.append(f'Hi {name}, the {position_title.title()}!')
        
    print('\n'.join(hello_strs))

In [82]:
hello_to_the_office(
    regional_manager='Michael',
    office_administrato='Pam',
    regional_co_manager='Jim',
    asssistant_to_the_regional_manager='Dwight'
)

Hi Michael, the Regional_Manager!
Hi Pam, the Office_Administrato!
Hi Jim, the Regional_Co_Manager!
Hi Dwight, the Asssistant_To_The_Regional_Manager!


Here's a more complicated function that also uses `**kwargs`

In [83]:
def report(to_print=True, **kwargs):
    
    # Effectively, kwargs is a dictionary
    the_keys = ';'.join(kwargs.keys())
    the_values = kwargs.values()
    
    # Note the safe way of getting the values
    if kwargs.get('is_bot'):
        print('ROBOT ALERT!!')
    
    if to_print:
        print(f'''
            The Keys:
                {the_keys}
            The Values:
                {the_values}
        ''')
    else:
        return the_keys, the_values

In [84]:
# Note that these arguments were never defined in the report() function
report(name='Fry', birth_year=1985)


            The Keys:
                name;birth_year
            The Values:
                dict_values(['Fry', 1985])
        


In [85]:
report(name='Bender', titanium_level=0.4, birth_year=2996, is_bot=True)

ROBOT ALERT!!

            The Keys:
                name;titanium_level;birth_year;is_bot
            The Values:
                dict_values(['Bender', 0.4, 2996, True])
        


We can also use the `**` operator to unpack a dictionary to a function as _named parameters_.

In [86]:
def named_parameter_function(param0, param1, default=10):
    return (param0, param1, default)

In [87]:
my_params = {'param0':'Zero', 'param1':10000, 'default':False}

named_parameter_function(**my_params)

('Zero', 10000, False)